// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2qUeSfo814sKK1SI0OE7eHY7hXC0Ne5w',
    appId: '1:359802914118:android:ad6d3df4b4f7c468f4d147',
    messagingSenderId: '359802914118',
    projectId: 'talabat-e4fdc',
    storageBucket: 'talabat-e4fdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6M6RRE_j3saHlPAD7AtDuv74NT3V-tIU',
    appId: '1:359802914118:ios:686c4cec920691b9f4d147',
    messagingSenderId: '359802914118',
    projectId: 'talabat-e4fdc',
    storageBucket: 'talabat-e4fdc.firebasestorage.app',
    iosBundleId: 'com.sixamtech.sixamMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6M6RRE_j3saHlPAD7AtDuv74NT3V-tIU',
    appId: '1:359802914118:ios:49f6e2e91bbea9c1f4d147',
    messagingSenderId: '359802914118',
    projectId: 'talabat-e4fdc',
    storageBucket: 'talabat-e4fdc.firebasestorage.app',
    iosBundleId: 'com.apmo.talabatcom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQTVXxHD_LWQRgcaRgCK8qpNhMBdhryqk',
    appId: '1:359802914118:web:b556bc4d7390c6cff4d147',
    messagingSenderId: '359802914118',
    projectId: 'talabat-e4fdc',
    authDomain: 'talabat-e4fdc.firebaseapp.com',
    storageBucket: 'talabat-e4fdc.firebasestorage.app',
    measurementId: 'G-G95T1YT477',
  );
}
