// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLFJsorOHaFc4nrRNtZ-eGpaq5CyqJbDs',
    appId: '1:1064328943216:web:fbec53c91c90c793e306b5',
    messagingSenderId: '1064328943216',
    projectId: 'talabatcom-b7817',
    authDomain: 'talabatcom-b7817.firebaseapp.com',
    storageBucket: 'talabatcom-b7817.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6U26DfQp32fOnvhHudjiBWI5Cvc4s_vo',
    appId: '1:1064328943216:android:33352f456399bb84e306b5',
    messagingSenderId: '1064328943216',
    projectId: 'talabatcom-b7817',
    storageBucket: 'talabatcom-b7817.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA9SYjBOlSI85dxtaln_K1CrBSmJi4kAA',
    appId: '1:1064328943216:ios:5f8815f365d90c00e306b5',
    messagingSenderId: '1064328943216',
    projectId: 'talabatcom-b7817',
    storageBucket: 'talabatcom-b7817.firebasestorage.app',
    iosBundleId: 'com.sixamtech.sixamMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA9SYjBOlSI85dxtaln_K1CrBSmJi4kAA',
    appId: '1:1064328943216:ios:0e37dc2fad7c7e5ce306b5',
    messagingSenderId: '1064328943216',
    projectId: 'talabatcom-b7817',
    storageBucket: 'talabatcom-b7817.firebasestorage.app',
    iosBundleId: 'com.yasser.talabatcom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLFJsorOHaFc4nrRNtZ-eGpaq5CyqJbDs',
    appId: '1:1064328943216:web:4c012742981da0fde306b5',
    messagingSenderId: '1064328943216',
    projectId: 'talabatcom-b7817',
    authDomain: 'talabatcom-b7817.firebaseapp.com',
    storageBucket: 'talabatcom-b7817.firebasestorage.app',
  );
}
